import puppeteer from 'puppeteer';
const API = process.env.KARAOKE_API;
const sleep = ms => new Promise(r=>setTimeout(r,ms));
const PID = (await (await fetch(API+'/api/state')).json()).projects[0].id;
const proj = async () => (await (await fetch(API+'/api/project/'+encodeURIComponent(PID))).json());
const d0 = await proj();
const bent = JSON.parse(JSON.stringify(d0.lines));
bent[0].end = bent[0].start + 0.15;
bent[0].words = bent[0].words.map(w => ({...w, t: bent[0].start, d: 0.05}));
await fetch(`${API}/api/project/${encodeURIComponent(PID)}/timings`, {method:'POST',
  headers:{'Content-Type':'application/json'}, body: JSON.stringify({lines: bent})});
const b = await puppeteer.launch({headless:'new', args:['--no-sandbox','--disable-dev-shm-usage']});
const p = await b.newPage();
p.on('console', m => console.log('PAGE:', m.text()));
p.on('pageerror', e => console.log('ERR:', String(e)));
await p.setViewport({width:1366, height:900});
await p.goto(API+'/', {waitUntil:'networkidle0'});
await sleep(500);
await p.click('.card');
await p.waitForSelector('#scrEdit:not(.hide)', {timeout:20000});
await sleep(800);
console.log('rows:', (await p.$$('#probs .prob')).length);
console.log('has ign:', !!(await p.$('#probs .prob .ign')));
await p.click('#probs .prob .ign');
await sleep(200);
console.log('rows после клика:', (await p.$$('#probs .prob')).length);
console.log('checkOff в окне:', await p.evaluate("typeof checkOff !== 'undefined' ? JSON.stringify(checkOff) : 'нет'"));
await sleep(1500);
console.log('rows после сохранения:', (await p.$$('#probs .prob')).length);
const saved = await proj();
console.log('checkOff на диске:', JSON.stringify(saved.checkOff));
console.log('problems с сервера:', JSON.stringify((saved.problems||[]).map(x=>x.kinds)));
await fetch(`${API}/api/project/${encodeURIComponent(PID)}/timings`, {method:'POST',
  headers:{'Content-Type':'application/json'}, body: JSON.stringify({lines: d0.lines, checkOff: []})});
await b.close();
